"""empty message

Revision ID: 22097681a369
Revises: aff03874a55e
Create Date: 2020-09-30 07:28:34.715165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22097681a369'
down_revision = 'aff03874a55e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('address', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'address')
    # ### end Alembic commands ###
